### ISSUE TITLE
Suggestion: Priority queue with a permission check.

### ISSUE THREAD

**Issue by KoxSosen** [flori4nk/VelocityAutoReconnect#10]
Hello!

Something I noticed while poking around with the plugin: If you shut down your backend with let's say 1 mod and 4 players on, and after the reboot the plugin sends back the players as expected.

However, if while the backend was down, and someone joined, and the mod reconnected or something like that, there is a chance that the mod get sent back to the backend as the last one. If the server has a cap of 4 players, the mod can get stuck in the limbo till someone leaves from the backend.

To avoid this, and always send back the users with the perm of let's say `var.priority`, please add an option to the config, to enable priority queue for the people who have this rank. 

Attention: *Please also add an option for this, if you decide to add it. If disabled please disable the permission check and all the logic behind the pirority queue. Why? From previus experience, permission checking with 70+ players on can get very heavy on the permission db serbur. It's propably better to set this to default to false, and document it carefully for the users to configure.*

**Comment by flori4nk** [comment]
Prerequisite: #22
