### ISSUE TITLE
Plugin straight up not working

### ISSUE THREAD

**Issue by MAXOUXAX** [flori4nk/VelocityAutoReconnect#19]
**Describe the bug**
I have configured my Limbo server in my Velocity configuration, added it to the try order AND the forced-hosts try order, the connection to the Limbo server works (I can do /server Limbo and it's taking me to the Limbo server before redirecting me to my previous server).
The plugin is also configured to use the correct server name AND kick message, but when I stop a server, it's just kicking me with the shutdown message but not taking me to the Limbo server.

**To Reproduce**
1. Configure everything (add Limbo server in Velocity configuration and try orders, configure the plugin to use the correct Limbo server name AND shutdown message)
2. Connect to the server
3. Stop the server
4. Getting kicked out

**Expected behavior**
I should be connected to the Limbo server and then redirected to my previous server when it comes back up.

**Configurations snippets**
velocity.toml
```toml
Limbo = "IP:PORT"

try = [
    "Server1",
    "Limbo"
]

[forced-hosts]
"server1.domain.tld" = [
    "Server1", "Limbo"
]
"dev.domain.tld" = [
    "Dev", "Limbo"
]
"build.domain.tld" = [
    "Build", "Limbo"
]
```

velocityautoreconnect.conf
```conf
directconnect-server=Server1
kick-filter.whitelist=Trying to connect you to Limbo server...
limbo-name=Limbo
```

bukkit.yml
```yml
shutdown-message: Trying to connect you to Limbo server...
```

**Comment by pwnker** [comment]
yeah i have the same problem.

**Comment by MAXOUXAX** [comment]
Can confirm it's now working!
Thanks :)
