### ISSUE TITLE
Plugin doesn't seem to function on legacy forwarding

### ISSUE THREAD

**Issue by pwnker** [flori4nk/VelocityAutoReconnect#20]
**Describe the bug**
I cant seem to get this plugin working as intended, may be due to the fact i am using velocity legacy forwarding for plugin compatibility. No errors in console and the plugin is active (directconnect-server does work as intended).

**To Reproduce**
1. Use legacy forwarding on velocity
2. Set up a limbo server and register it with velocity and add it to the try order
3. Use my config below.
4. Get connected to the first server in the try order but not the limbo server.

**Expected behavior**
The player gets connected to the limbo server and then gets reconnected.

**Additional context**
```
kick-filter.whitelist.enabled=false
directconnect-server=Hub
kick-filter.blacklist=.* ([Bb]anned|[Kk]icked).*
message.enabled=true
log.informational=true
pingcheck=true
kick-filter.whitelist=Server Closed
limbo-name=Limbo
message=&aYou are in limbo, you will be reconnected soon.
task-interval-ms=3500
kick-filter.blacklist.enabled=true
```

**Comment by flori4nk** [comment]
Are you sure the whitelist is disabled?
The value of kick-filter.whitelist.enabled is not included in the above config and is true by default.

**Comment by flori4nk** [comment]
Legacy forwarding shouldn't affect VelocityAutoReconnect, but I'll test it when I have time later today.

**Comment by pwnker** [comment]
> Are you sure the whitelist is disabled?
> The value of kick-filter.whitelist.enabled is not included in the above config and is true by default.

Yeah see edit, just confirmed that it is on my server as well.

**Comment by flori4nk** [comment]
Can't confirm. The following configuration is working:

- Velocity 3.0.0 with legacy forwarding
  - VelocityAutoReconnect 1.2.3
  - ViaVersion and ViaBackwards 4.0.1
- NanoLimbo 1.2.2 with legacy forwarding
- PaperMC 1.12.2 (1618)
