### ISSUE TITLE
No Multi Server support

### ISSUE THREAD

**Issue by pwnker** [flori4nk/VelocityAutoReconnect#26]
**Is your feature request related to a problem? Please describe.**
I have found the root cause to this plugin not working on my server (which i originally believed to be a problem with the whitelisting or my configuration #20). I have around 6 servers on my velocity proxy (not in the try order though) and my try order used to be `[hub, limbo]`. This creates a problem, when a player would get kicked from any server except the hub server they are not sent to limbo instead they are sent to the hub according to the try order. Not entirely sure if this is the intended way for the plugin to work. If not feel free to mark this as a bug report and I will edit my issue to match.

**Describe the solution you'd like**
Don't use the try order when sending a player to limbo. Instead send them directly there.

**Additional context**
My current workaround is to just have the try order `[limbo]` but having a player join limbo every time they join is not ideal.

**Comment by flori4nk** [comment]
This is intentional behavior.
