### ISSUE TITLE
Virtual Limbo server using LimboAPI by Elytrium

### ISSUE THREAD

**Issue by pseudoforceyt** [flori4nk/VelocityAutoReconnect#28]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Currently, the limbo server needs to be a separate server in order for it to work. With the [LimboAPI](https://github.com/Elytrium/LimboAPI) you can create virtual limbo servers within the velocity instance. Using this, please create a feature for virtual limbo where you dont need to host a separate server

**Additional context**
[Similar functionality to this](https://www.spigotmc.org/resources/automatic-server-reconnect-bungee-reconnect.84395/)

**Comment by flori4nk** [comment]
Sorry, but this would add a heavy dependency to the project. I never intended VelocityAutoReconnect to implement anything besides simple reconnection to/from servers in the network and am actually reconsidering many of the feature requests I previously decided to work on, as I don't want it to become too bloated.

> feature for virtual limbo where you dont need to host a separate server

LimboAPI essentially hosts a server and adds it to the proxy. Sure, it would make installation easier, but would also give users a lot less control over their network and I don't want that. Running a separate Limbo server software like NanoLimbo shouldn't take a lot of effort on an already existing network unless you are using a bad setup.

**Comment by flori4nk** [comment]
I also don't like the way it handles things. It does a lot of stuff without asking or providing any way to disable for the developers of projects it depends on (for example update check on proxy initialization) and interferes with the login process in a major way, which may or may not be necessary for its feature set, but it's not something I would want to add to VelocityAutoReconnect.

**Comment by hevav** [comment]
> LimboAPI essentially hosts a server and adds it to the proxy
You're wrong. LimboAPI only spawns players in a virtual world that works through low-level and highly optimized PreparedPackets and Velocity's built-in MinecraftPackets

**Comment by hevav** [comment]
> It does a lot of stuff without asking or providing any way to disable for the developers of projects that depend on it

Only the plugin does the update checking, the API side of LimboAPI doesn't do that

**Comment by flori4nk** [comment]
@hevav Thanks for clarifying, I have edited my previous comments. I don't think I was very awake when writing these comments ._.

Still, I don't want to add any dependencies to VelocityAutoReconnect for the other reasons I named above.
