### ISSUE TITLE
Whitelisted fallback server

### ISSUE THREAD

**Issue by projectaidan** [flori4nk/VelocityAutoReconnect#31]
**Describe the bug**
When the main server is whitelisted, and a player connects to it, they are forced to the fallback server. This is acting as intended. However, it would be great if VelocityAutoReconnect understood that those players which aren't on a whitelist should be ignored and not constantly try to send them to the main server. Instead, keep them on the fallback server.

**To Reproduce**
1. Whitelist 'x' player on main server
2. Have player connect to main server
3. They will be sent to fallback server
4. Watch as the main server console gets flooded with messages explaining that they are not whitelisted.

**Expected behavior**
It would be nice if VAR would leave those unwhitelised players alone. Possibly doing a check every 'X' amount of minutes. 

**Additional context**

**Comment by flori4nk** [comment]
Adding another feature for this is not necessary, since this functionality is already covered by the kick filter blacklist.

Here's the regular expression I use: `kick-filter.blacklist=.* ([Bb]anned|[Kk]icked|[Ww]hite[ -]?list).*`
