### ISSUE TITLE
Cant Direct join to the Limbo

### ISSUE THREAD

**Issue by Rajdave69** [flori4nk/VelocityAutoReconnect#33]
**Describe the bug**

**To Reproduce**
1. Go to 'Velocity.toml'
2. Set Try = `try = ["Limbo"]` (limbo being Limbo server)
3. Set VelocityServerReconnect config to - `directconnect-server=AuthServer` (Auth-Server being the server i want the plugin to connect to, IF player just joined through proxy, not getting kicked from another server)
4. See that player is not put in the Limbo and not connected to AuthServer through the directconnect-server config

**Expected behavior**
Player joins proxy - Goes into Limbo, and is moved to AuthServer. (main issue, player cant even connect)
Player gets kicked from another server/it goes down - Player is moved into limbo until that server is back up

**Additional context**
DM me on Discord if you want more info/my config files, etc. Raj Dave#3215

**Comment by flori4nk** [comment]
Please read the documentation and report back if you still have issues afterwards.
