### ISSUE TITLE
When main is shut down player is no longer sent to fallback Limbo

### ISSUE THREAD

**Issue by MODNMETL** [flori4nk/VelocityAutoReconnect#40]
### What happened?

Server shutdown does not send player to fallback Limbo server (Without this plugin the velocity.toml 'Try' order has main,limbo and main shutdown will normally send players to Limbo (but not back on restart obvs hence the need for your plugin)

### What did you expect to happen?

I expected the player to be sent to the Limbo server as normal when I shut down main. 

### Relevant log output

```shell
[13:40:55 INFO]: [connected player] l33tDad (/188.240.56.132:55309): kicked from server main: velocity.error.internal-server-connection-error
[13:40:55 INFO]: [server connection] l33tDad -> main has disconnected
[13:40:55 INFO]: [connected player] l33tDad (/188.240.56.132:55309) has disconnected: An internal server connection error occurred.
```

### velocityautoreconnect.conf

```shell
#VelocityAutoReconnect configuration -- Documentation: https://github.com/flori4nk/VelocityAutoReconnect/blob/master/README.md#configuration
#Fri Jun 24 11:26:02 UTC 2022
kick-filter.whitelist.enabled=true
directconnect-server=main
kick-filter.blacklist=.* ([Bb]anned|[Kk]icked).*
message.enabled=false
log.informational=true
pingcheck=true
kick-filter.whitelist=Server closed
limbo-name=limbo
message=You will be reconnected to Pinecraft shortly.
task-interval-ms=3500
kick-filter.blacklist.enabled=false
```

### I am sure that ...

- [X] I have actually read the documentation and that the error is not caused by my configuration.
- [X] I am using the latest version of VelocityAutoReconnect.
- [X] I have filled out every required field in this form (including the title field).

**Comment by MODNMETL** [comment]
Just to clarify on the above, this is on a 1.19 server

**Comment by flori4nk** [comment]
Try disabling the kick filter whitelist and see if it works, looks like you are being kicked from the server with the reason "velocity.error.internal-server-connection-error" which != "Server closed"

**Comment by MODNMETL** [comment]
Yep, that did the trick @flori4nk. Server shutdown successfully sent me to the limbo fallback and your plugin reconnected me on restart. Thanks for the help, much appreciated.

**Comment by RhinoCD** [comment]
So I did what you said, and your right, instead of saying Server closed, it does connect me to the limbo server now. For some reason after the server is back up though, its not sending me back to the main server. In addition to that, for some reason its only sending my player to the limbo server, and no one else. Everyone else receives the Timed Out message on their screen.

**Comment by flori4nk** [comment]
Oops, meant to reopen #38 .
