### ISSUE TITLE
Comments in the config.

### ISSUE THREAD

**Issue by KoxSosen** [flori4nk/VelocityAutoReconnect#8]
Hello!

Here is a little suggestion to avoid future confusion.

The current config is small, which I prefer over a huge list of usueless comments, but please add a wiki/some explanation to the whitelist/blacklist feature, because I think it can get confusing a bit.

**Comment by flori4nk** [comment]
The whitelist/blacklist options are explained in [README.md](https://github.com/flori4nk/VelocityAutoReconnect/blob/master/README.md), perhaps I could insert a link?

> kick-filter.blacklist
>
>    Default: .* ([Bb]anned|[Kk]icked).*
>    Description: If a kicked player falls back to the Limbo server and the reason matches this regular expression, they are disconnected.
>
> kick-filter.blacklist.enabled
>
>    Default: false
>
> kick-filter.whitelist
>
>    Default: Server closed
>    Description: If a kicked player falls back to the Limbo server and the reason does not match this regular expression, they are disconnected.
>
>kick-filter.whitelist.enabled
>
>    Default: true

**Comment by KoxSosen** [comment]
Yes please!

**Comment by flori4nk** [comment]
Will be added to 1.2.0 release
