### ISSUE TITLE
Suggestion: Get the players place in the queue as a placeholder.

### ISSUE THREAD

**Issue by KoxSosen** [flori4nk/VelocityAutoReconnect#9]
Hello! I opened a github issue for this suggestion to keep things organized.

The suggestion is an option in the config to turn on/off which enables you to use something like `%loc%` in the `message=` field in the config. This could he helpful for players to know their place in the queue to the backend. 

Attention: *Please add a config for this, because the logic that will calculate their place/location in the queue can be heavy depending on the amount of players. It's propably better to have this boolean option on false by default*

**Comment by flori4nk** [comment]
Prerequisite: #22
